config/routes.rb
Bacancy::Application.routes.draw do
  devise_for :users

  resources :users do
    resources :products
  end

  resources :states, only: :index
  resources :cities, only: :index
  resources :country, only: :index

  root 'users#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      if !user.new_record?
        can :edit, User, :id => user.id
        can :manage, Product, :user_id => user.id
      else
        can :read, :all
      end
    end
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :state

  validates_presence_of :name, uniqueness: true

  def self.all_by_state_name(state_name)
    joins(:state).where('states.name' => state_name)
  end
end

app/models/continent.rb
class Continent < ActiveRecord::Base
	has_many :countires
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :continent
  has_many :states

  validates :name, presence: true

   def self.all_by_continent_name(continent_name)
    joins(:continent).where('continents.name' => continent_name)
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
  belongs_to :country

  validates_presence_of :name

  def self.all_by_country_name(country_name)
    joins(:country).where('countries.name' => country_name)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products, dependent: :destroy
  validate :name, presence: true, uniqueness: true

  validates_format_of :mobile, with: /\A[1-9][0-9]{9}\Z/, allow_blank: true

  def admin?
    is_admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all_by_state_name(params[:state_name])

    respond_to do |format|
      format.json { render json: @cities.map(&:name) }
    end
  end
end

app/controllers/country_controller.rb
class CountryController < ApplicationController
	def index
  	@countries = Country.all_by_continent_name(params[:continent_name])

    respond_to do |format|
      format.json { render json: @countries.map(&:name) }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_user
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @user = User.find(params[:user_id])
    @products = @user.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = @user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to [@user, @product], notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@user, @product] }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [@user, @product], notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to user_products_url(@user) }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
  	#@states = State.all_by_country_name(params[:country_name])
    @states = State.all_by_country_name(params[:country_name])

    respond_to do |format|
      format.json { render json: @states.map(&:name) }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Product was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end
  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:address, :mobile, :country, :state, :city, :gender, :continent)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/country_helper.rb
module CountryHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bacancy" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Bacancy</a>
          <div class="container nav-collapse">
            <ul class="nav pull-left">
              <li><%= link_to 'Users', users_path %></li>
            </ul>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li><%= link_to "Signout (#{current_user.email})", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container main-content">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for([@user, @product], html: {multipart: true}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user, @product] %> |
<%= link_to 'Back', user_products_path(@user) %>

app/views/products/index.html.erb
<h3>Products for <%= @user.email -%></h3>

<div>
  <% if @products.empty? %>
    No products for this user
  <% else %>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Price</th>
          <th>User</th>
          <th>Image</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= product.user_id %></td>
            <td><%= image_tag product.image.url(:thumb) %></td>
            <td><%= link_to 'Show', [@user, product] %></td>
            <% if can? :manage, product %>
              <td><%= link_to 'Edit', edit_user_product_path(@user, product) %></td>
              <td><%= link_to 'Destroy', [@user, product], method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

<% if can?(:create, Product) && (@user == current_user || current_user.admin?) %>
  <%= link_to 'New Product', new_user_product_path(@user) %>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', user_products_path(@user) %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image.url %>
</p>

<% if can? :edit, @product -%>
  <%= link_to 'Edit', edit_user_product_path(@user, @product) %> |
<% end -%>
<%= link_to 'Back', user_products_path(@user) %>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:id => 'user-form', :class => 'form-horizontal'}) do |f| -%>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% unless @user.new_record? %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, disabled: true %>
    </div>
  </div>
<% end %>

<div class="control-group">
  <%= f.label :mobile, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :mobile %>
  </div>
</div>

<div class="control-group">
  <%= f.label :address, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :address %>
  </div>
</div>

<div class ="control-group">
  <%= f.label :continent, :class => 'control-label'%>
  <div class="controls">
    <%= f.select :continent, options_for_select([nil] + Continent.all.map(&:name))%>
  </div>
</div>


<div class="control-group">
  <%= f.label :country, :class => 'control-label' %>
  <div class="controls">
    <%= f.select :country, [], disabled: false%>
  </div>
</div>

<div class="control-group">
  <%= f.label :state, :class => 'control-label' %>
  <div class="controls">
    <%= f.select :state, [], disabled: true %>
  </div>
</div>

<div class="control-group">
  <%= f.label :city, :class => 'control-label' %>
  <div class="controls">
    <%= f.select :city, [], disabled: true %>
  </div>
</div>

<div class="controls">
  <%= f.submit class: 'btn' %>
</div>

<% end -%>

app/views/users/edit.html.erb
<%= form_for(@user, :html => {:class => 'form-horizontal'}) do |f| -%>

<h2> Edit <%= @user.email %></h2>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="control-group">
  <%= f.label :address, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :address %>
  </div>
</div>

<div class="control-group">
  <%= f.label :mobile, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :mobile %>
  </div>
</div>

<div class="control-group">
  <%= f.label :country, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :country %>
  </div>
</div>

<div class="control-group">
  <%= f.label :state, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :state %>
  </div>
</div>

<div class="control-group">
  <%= f.label :city, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :city %>
  </div>
</div>

<div class="controls">
  <%= f.submit class: 'btn' %>
</div>

<% end -%>

app/views/users/index.html.erb
<h3>List of users</h3>
<div>
  <% @users.each do |user| %>
    <div style="border:1px dotted gray; margin: 5px;">
      <%= user.email %>
      <%= link_to "Products (#{user.products.count})", user_products_path(user) %>
      <% if can? :manage, user -%>
        <%= link_to 'Edit', edit_user_path(user) %>
      <% end -%>
      <% if can?(:delete, user) && user != current_user %>
        <%= link_to 'Delete', user_path(user), method: :delete %>
      <% end %>
    </div>
  <% end %>
</div>
<div>
  <% if can? :create, User %>
    <%= link_to 'Create user', new_user_path %>
  <% end %>
</div>

app/views/users/new.html.erb
<h3>New user</h3>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2><%= @user.email %></h2>

<div class="row-fluid">
  <div class="span2">Address</div>
  <div class="span10">
    <%= @user.address %>
  </div>
</div>

<div class="row-fluid">
  <div class="span2">Mobile</div>
  <div class="span10">
    <%= @user.mobile %>
  </div>
</div>

<div class="row-fluid">
  <div class="span2">Country</div>
  <div class="span10">
    <%= @user.country %>
  </div>
</div>

<div class="row-fluid">
  <div class="span2">State</div>
  <div class="span10">
    <%= @user.state %>
  </div>
</div>

<div class="row-fluid">
  <div class="span2">City</div>
  <div class="span10">
    <%= @user.city %>
  </div>
</div>